name: SERVER_DEV

on:
  push:
    branches:
      - develop

jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Stop the Server
        uses: appleboy/ssh-action@master
        with:
          key: ${{secrets.SSH_KEY}}
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          script: |
            pm2 kill

      - name: Clone git repo
        uses: appleboy/ssh-action@master
        with:
          key: ${{secrets.SSH_KEY}}
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          script: |
            cd CandyKorean-Server
            git reset --hard
            git fetch
            git checkout develop
            git pull origin develop

      - name: Build TypeScript to JavaScript
        uses: appleboy/ssh-action@master
        with:
          key: ${{secrets.SSH_KEY}}
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          script: |
            cd CandyKorean-Server
            npm install
            npm run tsc

      - name: Start the Server
        uses: appleboy/ssh-action@master
        with:
          key: ${{secrets.SSH_KEY}}
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          script: |
            cd CandyKorean-Server
            pm2 start build/server.js